### ISSUE TITLE
能添加一个直接保存为mp3的函数吗? 

### ISSUE THREAD

**Issue by kyjdp** [Entity-Now/Edge_tts_sharp#1]
非常不错的项目,  在 .net 4.62 和. net core7 都能成功运行!

请问能添加一个直接保存为mp3的函数吗?  现在只能等播放完才能保存, 谢谢

另外, 在.net4.62下 引用的system和Microsoft开头的dll, 能使用系统自带的吗? 我尝试删除它们, 但是报错
我尝试git上的另一个.net4.62 版本的edge TTS, 只有两个dll, 能运行, 但是存成的mp3是断断续续的

**Comment by Entity-Now** [comment]
第一个问题已经解决了，你调用新接口（saveAudio）即可。
第二个问题我不大明白

**Comment by kyjdp** [comment]
> 第一个问题已经解决了，你调用新接口（saveAudio）即可。 第二个问题我不大明白
多谢, 
关于第二个问题, 请看下图, 粉色框中的dll 好像win10系统已经自带, 如果是.net core 有这些依赖能理解, 但是如果在 .net4.62 下调用时最好能调用系统里内置的dll就好多了, 我见过好多程序是这样的逻辑, 例如 https://www.nuget.org/packages/EdgeTTS 这个只用到了两个dll, 它没有播放功能, 所以没有NAudio那些dll 
![we](https://github.com/Entity-Now/Edge_tts_sharp/assets/6350504/18e60fd8-d50a-42c9-abcc-2c2a3a2e212b)

**Comment by Entity-Now** [comment]
这些动态链接库都是System.Text.Json的依赖，没办法删除的，除非换newtonsoft。
没必要纠结这几个文件，如果你实在不想要，可以自己改用newtonsoft。
