### ISSUE TITLE
禁止日志输出

### ISSUE THREAD

**Issue by ichat001** [Entity-Now/Edge_tts_sharp#3]
我在调试时, 总会在输出栏显示Edge调用的详细日志, 能禁止输出日志信息吗? 因为对调试有些影响, 或者添加一个开关, 能启用或禁用日志输出

**Comment by Entity-Now** [comment]
有时间优化一下

**Comment by Entity-Now** [comment]
你好，已经解决，使用全局变量Edge_tts.Debug即可屏蔽
