### ISSUE TITLE
似乎接口用不了了

### ISSUE THREAD

**Issue by tp1415926535** [Entity-Now/Edge_tts_sharp#6]
`Edge_tts.GetPlayer()` 无限卡住，昨天好像还可以

**Comment by tp1415926535** [comment]
另一个库有相似问题：[edge-tts#290](https://github.com/rany2/edge-tts/issues/290)

**Comment by GHFXJ1680** [comment]
同问, 还有解吗?

**Comment by tp1415926535** [comment]
> 同问, 还有解吗?

看一下fork的这个项目的其他仓库，有更新

**Comment by Entity-Now** [comment]
抄了下作业，已修复。
